spring:
  profiles:
    active: local
  application:
    name: Student-Data-Portal-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student-data
    username: postgres
    password: postgres
#    schema: student-data
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        default_schema: student-data # Custom schema name for Hibernate
server:
  port: 7777
#  servlet:
#    context-path: /api

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html






